### ISSUE TITLE
Register a shortcut in the EverythingToolbar

### ISSUE THREAD

**Issue by Johndo1234** [srwi/EverythingToolbar#436]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

Hello.
I would like to request adding an option to EverythingToolbar that allows registering shortcuts and launching them with one click.
This would make it easier to access frequently used files, and in the case of files used less frequently, it would allow accessing them from the search bar, providing differentiation of usage. I think this could make the tool more convenient for some users like me.

![everything-toolbar-1536x864 (1)](https://github.com/srwi/EverythingToolbar/assets/78249741/b97e770d-b567-4cbd-873c-a7cdf76c9291)

### Proposed Solution

To add a feature that enables registering arbitrary shortcuts to EverythingToolbar, allowing users to launch files/programs with a single click.

### Alternatives Considered

I don't have any now.

### Additional Information

I think this feature has likely not been implemented in Everything yet.

**Comment by srwi** [comment]
Hi @Johndo1234, I don't really see the relation of your feature request to EverythingToolbar since it doesn't use any search functionality. 

There is a somewhat similar request in #186.

Given that your requested feature is already implemented in the Windows start menu and the above points I will close this ticket. Sorry about that.
