### ISSUE TITLE
Open the default folder when clicked.

### ISSUE THREAD

**Issue by Grey1024** [srwi/EverythingToolbar#443]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

I need a toolbar quick launch software that can open software quickly, but I couldn’t find one after searching for a long time. Until I found this software, it is exactly what I need. However, I hope to add a feature, for example: when I first click this button, it will load the contents of a folder specified by me. This folder contains the software I frequently use. In this way, I can use it as a shortcut launcher. Additionally, if possible, I hope it can support shortcut key functions.

### Proposed Solution

As mentioned above.

### Alternatives Considered

As mentioned above.

**Comment by srwi** [comment]
This can already be done:

1. Create a custom filter in Everything:

    ![grafik](https://github.com/srwi/EverythingToolbar/assets/17520641/31bcf9e5-352d-4805-a5b6-201cae986431)

    This will search for all shortcuts inside your folder.

    If you don't want to include subfolders in the search results your filter could look like this:

    ![grafik](https://github.com/srwi/EverythingToolbar/assets/17520641/c359d7ac-1985-4e99-a85a-606c2fd73f31)

2. In EverythingToolbar check the following settings:
     - Use Everything filters
     - Remember filter
3. Select the custom filter (in this case "Applications") from the dropdown in EverythingToolbar

    ![grafik](https://github.com/srwi/EverythingToolbar/assets/17520641/24ea0ca8-c9e3-4059-a35d-4d335ae3fa30)



Next time you open EverythingToolbar the filter should still be selected so that you can directly search for applications.

**Comment by Grey1024** [comment]
Thank you very much for your guidance. I have successfully achieved it using the method you provided. However, I feel it is not perfect:


![image](https://github.com/srwi/EverythingToolbar/assets/133519197/3cee36b0-9637-4730-a3a2-87f71ebe43b2)



If I want to click to search for files, I have to go through additional steps to select a filter.
If the filter I selected last time was not my application filter, I cannot quickly open the software.
My idea is to set a default filter to be loaded when clicked, and once there is text input, the "all" filter will be used.

**Comment by Grey1024** [comment]
Translation: It might be clearer to use a different logic.
When there is no input condition, the default display should be the contents of the specified folder, rather than implementing it based on a filter.

**Comment by srwi** [comment]
> If it is not implemented based on filters, the logic will be clearer. I see that there is already an option in the current settings to "not display empty searches". So, if it is possible to set it to display the contents of a specific folder by default when there is an empty search, that would be perfect!

I understand your request and I thought about possible solutions. I think the best approach would be to do it with Everything's home settings. In Everything you can define a startup search term that will be pre-filled when opening Everything. In your case this could be the search term that lists all files in a specific folder.

Home settings are not yet available in EverythingToolbar but there is an open feature request for that: https://github.com/srwi/EverythingToolbar/issues/378

Since an issue for this already exists, I will close this issue as a duplicate. Thank you for your request!
