### ISSUE TITLE
The cvs file cannot be updated with Everything, will it be obtained automatically?

### ISSUE THREAD

**Issue by jp1017** [srwi/EverythingToolbar#517]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.4.0

### Everything Version

1.4.1.1024 x64

### Windows Version

win11

### Steps to reproduce

选择cvs时，是在everythings导出cvs，保存后，然后toolbar再选择此文件。那多个硬盘，优盘等频繁使用的，cvs变化很大，需要每次导出后，再引用？

### Expected Behavior

cvs随everythings更新及时更新

### Actual Behavior

cvs随everythings更新及时更新

### Log output

cvs随everythings更新及时更新

**Comment by srwi** [comment]
EverythingToolbar tracks changes in the filters.csv file automatically and updates the filters automatically. For that the option "Use Everything filters" has to be enabled.

What do you mean by changing hard drives? Do you want to use multiple different csv files for storing filters? I am not sure I understand your question correctly (possibly due to translation problems).

**Comment by jp1017** [comment]
First, I used Everythings to export filters.csv, and then used the EverythingToolbarto select this file. This caused the csv file not to be updated. So how to update?

**Comment by Horst12** [comment]
You should point the toolbar to the original place in Everything, thats all.
Everything updates it and the toolbar uses it.
______________________________________________________
Windows 11 Home x64 Version 23H2 (OS Build 22631.3880)
Everything 1.5.0.1383a (x64), Everything Toolbar 1.3.4

**Comment by jp1017** [comment]
Get it. 3KS
