### ISSUE TITLE
Search compatibility with startisback and startallback programs

### ISSUE THREAD

**Issue by DinacoStudio** [srwi/EverythingToolbar#529]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

Search in startisback & startallback is standart

### Proposed Solution

Hide standart & Inject Search in startisback & startallback

### Alternatives Considered

no

**Comment by srwi** [comment]
Hi, unfortunately I don't understand the problem. Can you please describe it in more detail?

I tested EverythingToolbar with StartAllBack and it should be working as intended. There are setup instructions for the Deskband variant (which is the one you want to use with StartAllBack/StartIsBack) [in the readme](https://github.com/srwi/EverythingToolbar?tab=readme-ov-file#deskband).

**Comment by arturnobre2002** [comment]
Hello! Sorry to necro, but the deskband search function in StartAllBack is not working for me. I am unsure if this is a bug or just intended behavior. Replying here because I was checking for past issues to see if there was anything similar to my problem. Search function works perfectly in the icon next to the system tray, I was just curious if there's any way to use it in the search bar where it reads "Search programs and files". 

<img width="353" height="263" alt="Image" src="https://github.com/user-attachments/assets/60d61451-7b0f-4ece-8f4b-ff307261c0ff" />


What I've tried:
- Installing executable from releases and winget
- Making sure Everything version is >=1.4.1 and running in the background
<img width="561" height="517" alt="Image" src="https://github.com/user-attachments/assets/12717997-b795-406c-86d0-94b79f0bd67a" />


- Unlocking taskbar and selecting EverythingToolbar
<img width="568" height="401" alt="Image" src="https://github.com/user-attachments/assets/ef1588bf-f0a2-46f6-afce-ac59b4ab2ad2" />




Thank you for reading, appreciate it!

**Comment by srwi** [comment]
Unfortunately EverythingToolbar is not designed to work that way. If anything that would have to be a feature of StartAllBack.

**Comment by VVispy** [comment]
@srwi how does the startallback integration work? I thought the same as @Kediny as it is written that deskband is applied to startallback.
